Repository nathanbell806/310A1BudgetTracker, pull requests merged in 2023-08, with the labels that each got.

#2 Code of conduct
  CODE_OF_CONDUCT.md
  README.md
Labels: documentation

#29 Pie chart view
  src/main/java/com/example/budgettracker/BudgetOverviewController.java
  src/main/java/com/example/budgettracker/HelloApplication.java
  src/main/java/com/example/budgettracker/HelloController.java
  src/main/resources/Images/arrow_back_FILL0_wght400_GRAD0_opsz48.png
  src/main/resources/com/example/budgettracker/budget_overview.fxml
  src/main/resources/com/example/budgettracker/hello-view.fxml
Labels: enhancement

#32 Create new templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: documentation

#37 Pie chart bug fix
  src/main/resources/com/example/budgettracker/budget_overview.fxml
Labels: bug

#44 New json tests to solve #41
  .github/workflows/build.yml
  src/main/java/com/example/budgettracker/controller/CreateProfileController.java
  src/main/java/com/example/budgettracker/profiles/CurrentProfile.java
  src/main/java/com/example/budgettracker/profiles/Expense.java
  src/main/java/com/example/budgettracker/profiles/Profile.java
  src/main/java/com/example/budgettracker/profiles/ProfileFactory.java
  src/main/java/com/example/budgettracker/profiles/ProfileRepository.java
  src/main/java/data/player_data.json
  src/test/java/tests/ProfileTest.java
  src/test/java/tests/controller/BudgetEntryControllerTest.java
Labels: bug

#47 build.yml changed for sonar #46
  .github/workflows/build.yml
Labels: bug

#49 Contributor guideline #4
  CONTRIBUTING.md
  target/classes/Images/arrow_back_FILL0_wght400_GRAD0_opsz48.png
  target/classes/com/example/budgettracker/budget_overview.fxml
Labels: documentation

#57 Json budget solve issue #51
  src/main/java/com/example/budgettracker/StartApplication.java
  src/main/java/com/example/budgettracker/profiles/Profile.java
  src/main/java/com/example/budgettracker/profiles/ProfileRepository.java
  src/test/java/tests/ProfileTest.java
Labels: bug

#59 Budget entry logic #58
  src/main/java/com/example/budgettracker/controller/BudgetEntryController.java
  src/main/java/com/example/budgettracker/profiles/ProfileRepository.java
  src/test/java/tests/ProfileTest.java
Labels: enhancement

#67 Remove profile factory solve issue #65
  src/main/java/com/example/budgettracker/BudgetCategoriesController.java
  src/main/java/com/example/budgettracker/CategoryItemController.java
  src/main/java/com/example/budgettracker/ChangeScene.java
  src/main/java/com/example/budgettracker/controller/BudgetEntryController.java
  src/main/java/com/example/budgettracker/controller/BudgetOverviewController.java
  src/main/java/com/example/budgettracker/controller/CreateProfileController.java
  src/main/java/com/example/budgettracker/controller/SelectProfileController.java
  src/main/java/com/example/budgettracker/profiles/ProfileFactory.java
  src/main/java/com/example/budgettracker/profiles/ProfileRepository.java
  src/test/java/tests/ProfileTest.java
  src/test/java/tests/controller/BudgetEntryControllerTest.java
Labels: enhancement

#72 UI budget entry scene
  src/main/java/com/example/budgettracker/controller/BudgetEntryController.java
  src/main/java/data/player_data.json
  src/main/resources/com/example/budgettracker/budget-entry.fxml
Labels: enhancement

#71 Get piechart data #66
  src/main/java/com/example/budgettracker/ChangeScene.java
  src/main/java/com/example/budgettracker/SceneName.java
  src/main/java/com/example/budgettracker/controller/BudgetOverviewController.java
  src/main/resources/com/example/budgettracker/budget-overview.fxml
  src/main/resources/com/example/budgettracker/budget_overview.fxml
  target/classes/com/example/budgettracker/budget_overview.fxml
Labels: enhancement

#73 Set user budget value #70
  src/main/java/com/example/budgettracker/BudgetCategoriesController.java
Labels: enhancement

#76 Connected BudgetCategoriesController to the Overview summary #75
  src/main/java/com/example/budgettracker/BudgetCategoriesController.java
  src/main/resources/com/example/budgettracker/budget-categories.fxml
Labels: enhancement
